### ISSUE TITLE
zookeeper_seeds_path not read correctly on cass 2.2.0

### ISSUE THREAD

**Issue by mihasya** [kow3ns/cassandra-zookeeper-seedprovider#1]
I cannot get Cassandra to correctly read the `zookeeper_seeds_path` param. I keep getting this error:

```
ERROR [main] 2016-01-28 20:33:50,651 ZooKeeperSeedProviderConfig.java:156 - zookeeper_seeds_path must be set to a ZNode path in cassandra.yaml
ERROR [main] 2016-01-28 20:33:50,658 ZooKeeperSeedProvider.java:128 - invalid configuration
io.mesosphere.mesos.frameworks.cassandra.MissingConfigException: [zookeeper_seeds_path] is mandatory for ZookeeperSeedProvider
    at io.mesosphere.mesos.frameworks.cassandra.ZooKeeperSeedProviderConfig.validate(ZooKeeperSeedProviderConfig.java:161) ~[zookeeper-seedprovider-1.0.jar:na]
    at io.mesosphere.mesos.frameworks.cassandra.ZooKeeperSeedProviderConfig.<init>(ZooKeeperSeedProviderConfig.java:116) ~[zookeeper-seedprovider-1.0.jar:na]
    at io.mesosphere.mesos.frameworks.cassandra.ZooKeeperSeedProviderConfig.from(ZooKeeperSeedProviderConfig.java:269) ~[zookeeper-seedprovider-1.0.jar:na]
    at io.mesosphere.mesos.frameworks.cassandra.ZooKeeperSeedProvider.<init>(ZooKeeperSeedProvider.java:112) ~[zookeeper-seedprovider-1.0.jar:na]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.7.0_75]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [na:1.7.0_75]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.7.0_75]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [na:1.7.0_75]
    at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:600) [apache-cassandra-2.2.0.jar:2.2.0]
    at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:111) [apache-cassandra-2.2.0.jar:2.2.0]
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:476) [apache-cassandra-2.2.0.jar:2.2.0]
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:588) [apache-cassandra-2.2.0.jar:2.2.0]
```

I've read the code and everything LOOKS correct. I can confirm that other options, such as `zookeeper_server_addresses` are being read correctly because I get the appropriate error when I take those out. I've tried a whole bunch of different spacing arrangements (probably have covered everything Yaml will allow at this point) but it just won't go. Here's the state it's in now:

```
seed_provider:
  - class_name: "io.mesosphere.mesos.frameworks.cassandra.ZooKeeperSeedProvider"
    parameters:
    - zookeeper_server_addresses : "10.10.3.135:2181,10.10.3.38:2181,10.10.3.136:2181"
    - zookeeper_seeds_path : "/cassandra22/seeds"
    - session_timout_ms : 10000
```

Any ideas?

**Comment by mihasya** [comment]
Confirming same problem with 2.2.4
